// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXRrza_9BZo_qQBhC0h5lzUmX9PPpJwg0',
    appId: '1:14010318993:android:7cc784178b29005fc77f30',
    messagingSenderId: '14010318993',
    projectId: 'chinatownmain-febce',
    storageBucket: 'chinatownmain-febce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0z8_oSaWmg_x56Yu6eDPoSfhAoAb5o0A',
    appId: '1:14010318993:ios:fc7b8456de58d158c77f30',
    messagingSenderId: '14010318993',
    projectId: 'chinatownmain-febce',
    storageBucket: 'chinatownmain-febce.appspot.com',
    androidClientId: '14010318993-sijb95se1hohm7vog9e6tcm64gmi9uk3.apps.googleusercontent.com',
    iosClientId: '14010318993-6he1urk9orcua24rff30o2ek3ej64ome.apps.googleusercontent.com',
    iosBundleId: 'com.example.dummy1',
  );

}